[theme]
base = "light"
primaryColor = "#1FBC59"
backgroundColor = "#F1F4F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
